#!/bin/sh

mkdir cmake_environment_set
mkdir how_C++_works
mkdir compiler
mkdir linker
mkdir variables
mkdir funcions
mkdir header_files
mkdir gbd_debug
mkdir conditions_and_branches
mkdir loops
mkdir control_flow
mkdir pointers
mkdir references
mkdir classes
mkdir classes_vs_structs
mkdir how_to_write_a_class
mkdir static
mkdir static_for_classes_and_structs
mkdir local_static
mkdir enums
mkdir constructors
mkdir destructors
mkdir inheritance
mkdir virtual_funciton
mkdir interfaces_pure_virtual_funciton
mkdir visibility
mkdir arrays
mkdir how_strings_work_in_c++
mkdir string_literals
mkdir const
mkdir mutale
mkdir member_initializer_lists
mkdir ternary_operators
mkdir how_to_create_or_instantiate_objects
mkdir new
mkdir implicit_conversion_and_the_explicit_keyword
mkdir operators_and_operator_overloading
mkdir this
mkdir object_lifetime
mkdir smart_pointers
